<?php 

return [
    'Latitud' => 'latitude',
    'Longitud' => 'longitude',
    'ID' => 'id',
    'Titulo' => 'title',
    'Anunciante' => 'advertiser',
    'Descripcion' => 'description',
    'Reformado' => 'refurbished',
    'Telefonos' => 'phones',
    'Tipo' => 'type',
    'Precio' => 'price',
    'Precio por metro' => 'price_per_sqm',
    'Direccion' => 'address',
    'Provincia' => 'province',
    'Ciudad' => 'city',
    'Metros cuadrados' => 'square_meters',
    'Habitaciones' => 'bedrooms',
    'Baños' => 'bathrooms',
    'Parking' => 'parking',
    'Segunda mano' => 'second_hand',
    'Armarios Empotrados' => 'built_in_wardrobes',
    'Construido en' => 'built_in',
    'Amueblado' => 'furnished',
    'Calefacción individual' => 'individual_heating',
    'Certificación energética' => 'energy_certification',
    'Planta' => 'floor',
    'Exterior' => 'exterior',
    'Interior' => 'interior',
    'Ascensor' => 'elevator',
    'Fecha' => 'date',
    'Calle' => 'street',
    'Barrio' => 'neighborhood',
    'Distrito' => 'district',
    'Terraza' => 'terrace',
    'Trastero' => 'storage_room',
    'Cocina Equipada' => 'equipped_kitchen',
    'Aire acondicionado' => 'air_conditioning',
    'Piscina' => 'swimming_pool',
    'Jardín' => 'garden',
    'Metros cuadrados útiles' => 'usable_square_meters',
    'Apto para personas con movilidad reducida' => 'suitable_for_reduced_mobility',
    'Plantas' => 'floors',
    'Se admiten mascotas' => 'pets_allowed',
    'Balcón' => 'balcony',
];